Testing failure condition

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,7 +13,7 @@ jobs:
       app-version: ${{ steps.version.outputs.version }}
 
     env:
-      APP_ENV: production
+      APP_ENV: development
       APP_NAME: Notes-App
     steps:
       - name: checkout code
@@ -32,8 +32,13 @@ jobs:
           else
             echo "Secret exists: false"
           fi
-             
-
+      - name: Intentional failure
+        run: exit 1
+      - name: Failure message
+        if: failure()
+        run: echo " A previous step failed!"
+            
+      
       - name: test
         run: echo "testing...."
       - name: Development check
